# Documentation for this configuration: https://embarkstudios.github.io/cargo-deny/checks/cfg.html

[advisories]
ignore = []

[licenses]
# https://spdx.org/licenses/
# https://spdx.org/licenses/Unicode-DFS-2016.html
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MITNFA",
    "MPL-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.93
private = { ignore = true }

# Add exceptions for non-standard licenses on specific crates
[[licenses.exceptions]]
name = "ring"
allow = ["OpenSSL"]
[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
