[alias]
clippy-all = ["clippy", "--frozen", "--workspace", "--all-targets", "--", "--deny", "warnings"]
clippy-all-update-crates = ["clippy", "--workspace", "--all-targets", "--", "--deny", "warnings"]
crit = ["bench", "--bench", "parse_issue"]
deny-check-offline = ["deny", "check", "--disable-fetch", "--allow", "unnecessary-skip"]
deny-check-update = ["deny", "check", "--allow", "unnecessary-skip"]
deny-init = ["deny", "init"]
deny-install = ["install", "--locked", "cargo-deny"]
doc-all = ["doc", "--frozen", "--workspace", "--all-features", "--document-private-items",  "--keep-going"]
doc-all-update-crates = ["doc", "--workspace", "--all-features", "--document-private-items", "--keep-going"]
test-all = ["test", "--frozen", "--workspace", "--all-targets", "--no-fail-fast", "--"]
test-ignored = ["test", "--frozen", "--workspace", "--all-targets", "--no-fail-fast", "--", "--ignored"]
test-all-update-crates = ["test", "--workspace", "--all-targets", "--no-fail-fast", "--"]
ir = ["insta", "review", "--workspace"]
insta-snapshots-unused-find = ["insta", "test", "--unreferenced=reject"]
insta-snapshots-unused-delete = ["insta", "test", "--unreferenced=delete"]
